defaults:
  - single
  - _self_

data:
  fold_dir: '/data/pathology/projects/ais-cap/dataset/visiomel/splits'

features_dir: '/data/pathology/projects/ais-cap/code/git/clemsgrs/hipt/output/visiomel/features/4096_tcga/38l9c9xk/features/global/slide'
output_dir: 'output/visiomel'
experiment_name: 'classification'
level: 'global'

nepochs: 50
num_classes: 2
label_name: 'relapse'

task: 'classification'
loss: 'ce'

training:
  weighted_sampling: False

testing:
  retrieve_checkpoint: 'best'

model:
  dropout: 0.25

wandb:
  enable: True
  project: 'hipt'
  username: 'clemsg'
  exp_name: '${experiment_name}'
  dir: '/home/user'
  to_log: ['loss', 'auc']
  group: