region_dir: ''

output_dir: 'output'
experiment_name: 'debug'
resume: False

slide_list:

region_size: 4096
format: 'jpg'
level: 'global'

pretrain_256: 'checkpoints/vit_256_small_dino.pth'
freeze_256: True

pretrain_4096: 'checkpoints/vit_4096_xs_dino.pth'
freeze_4096: True

wandb:
  project: 'hipt'
  username:
  exp_name: '${experiment_name}'
  dir: '/home/user/'