region_dir: '/data/pathology/projects/ais-cap/code/git/clemsgrs/hs2p/output/witali-liver_packed/patches'

output_dir: 'output'
experiment_name: 'witali-liver_indiv_debug'
resume: False

slide_list: '/data/pathology/projects/ais-cap/dataset/witali-liver/tmp.txt'

region_size: 4096
patch_size: 256
mini_patch_size: 16

format: 'jpg'
level: 'global'
save_region_features: True

pretrain_vit_patch: 'checkpoints/vit_256_small_dino.pth'
pretrain_vit_region: 'checkpoints/vit_4096_xs_dino.pth'

wandb:
  enable: True
  project: 'hipt'
  username: 'clemsg'
  exp_name: '${experiment_name}'
  dir: '/home/user/'
  group:

hydra:
  run:
    dir: /tmp/hydra_output