region_dir: '/data/pathology/projects/ais-cap/dataset/witali-liver/hs2p/packed/patches/4096/jpg'

output_dir: '/data/pathology/projects/ais-cap/code/git/clems/hipt/output/witali-liver'
experiment_name: 'feature_extraction'
resume: False

slide_list:

region_size: 4096
patch_size: 256
mini_patch_size: 16

format: 'jpg'
level: 'local'
save_region_features: True

pretrain_vit_patch: '/data/pathology/projects/ais-cap/dataset/witali-liver/hipt/dino/vit_256_small_dino.pth'
# pretrain_vit_region: 'checkpoints/vit_4096_xs_dino.pth'
pretrain_vit_region: ''

wandb:
  enable: True
  project: 'hipt'
  username: 'clemsg'
  exp_name: '${experiment_name}'
  dir: '/home/user/'
  group:

hydra:
  run:
    dir: /tmp/hydra_output