region_dir: '/home/user/code/git/cpg/hs2p/output/panda_dino/patches/2048/jpg'

output_dir: 'output'
experiment_name: 'dino'
resume: False

slide_list:

region_size: 2048
patch_size: 256
mini_patch_size: 16

format: 'jpg'

pretrain_vit_patch: 'checkpoints/vit_256_small_dino.pth'
freeze_vit_patch: True

wandb:
  enable: True
  project: 'hipt'
  username: 'clemsg'
  exp_name: '${experiment_name}'
  dir: '/home/user/'
  group: