data_dir: 'data'
output_dir: 'output'
features_dir:

dataset_name: 'tcga_brca'
data_csv: '${data_dir}/${dataset_name}/data.csv'
slide_list: '${data_dir}/${dataset_name}/slide_list.txt'

nepochs: 50
num_classes: 2
label_name: 'label'
label_mapping:
tune_every: 1

model:
  pretrain_256: 'checkpoints/vit_256_small_dino.pth'
  freeze_256: True
  freeze_256_pos_embed: True
  img_size_256: 224
  patch_size_256: 16
  pretrain_4096: 'checkpoints/vit_4096_xs_dino.pth'
  freeze_4096: True
  freeze_4096_pos_embed: True
  img_size_4096: 3584
  patch_size_4096: 256
  dropout: 0.25

optim:
  name: 'adam'
  lr: 2e-4
  wd: 1e-5
  lr_scheduler:
    name:

weighted_sampling: True
gradient_clipping: 32

pct:

train_batch_size: 1
tune_batch_size: 1

save_all: False

wandb:
  project: 'hipt'
  username: 'clemsg'
  exp_name: 'toy_training'
  dir: '/home/user/wandb'
  metrics_to_log: ['auc', 'roc_auc_curve']