defaults:
  - default
  - _self_

dataset_name: 'tcga_brca'
data_csv:
slide_list:

fold_num: 0
level: 'local'

nepochs: 100
num_classes: 2
tune_every: 1

model:
  img_size_4096: 4096
  freeze_4096: False
  freeze_4096_pos_embed: False
  dropout: 0.25

optim:
  name: 'adam'
  lr: 2e-4
  wd: 1e-5

early_stopping:
  enable: False
  tracking: 'loss'
  min_max: 'min'
  patience: 10
  min_epoch: 50

wandb:
  project: 'hipt'
  exp_name: 'toy_training'
  username: 'clemsg'