data_dir: '../hs2p/output/'

size: 'small'
dropout: 0.25
num_classes: 2

pretrain_256: 'checkpoints/vit_256_small_dino.pth'
freeze_256: False

pretrain_4096: 'checkpoints/vit_4096_xs_dino.pth'
freeze_4096: False