data_dir: 'data'
output_dir: 'output'

region_dir:
features_dir:

dataset_name: 'tcga_brca'
data_csv:
slide_list:

fold_num: 0
level: 'global'

num_classes: 2
nepochs: 50
tune_every: 1

model:
  img_size_496:
  patch_size_4096:
  pretrain_4096:
  freeze_4096:
  dropout: 0.25

optim:
  name: 'adam'
  lr: 2e-4
  wd: 1e-5
  lr_scheduler:
    name:

weighted_sampling: True
gradient_clipping: 32

pct:

train_batch_size: 1
tune_batch_size: 1

save_all: False

early_stopping:
  enable: True
  tracking: 'loss'
  min_max: 'min'
  patience: 10
  min_epoch: 30

wandb:
  project: 'hipt'
  exp_name: 'toy_training'
  username: 'clemsg'