data_dir: 'data'
output_dir: 'output'
region_dir: '${data_dir}/tcga_brca/patches'

dataset_name: 'toy'
# slide_list:
# data_csv:
slide_list: '${data_dir}/${dataset_name}/slide_list.txt'
data_csv: '${data_dir}/tcga_brca/data.csv'
resume: False

region_size: 4096
format: 'jpg'
level: 'local'

pretrain_256: 'checkpoints/vit_256_small_dino.pth'
freeze_256: True

pretrain_4096: 'checkpoints/vit_4096_xs_dino.pth'
freeze_4096: True

wandb:
  project: 'hipt'
  exp_name: 'feature_extraction'
  username: 'clemsg'