data_dir: 'data/'
output_dir: 'output/'

region_size: 4096
level: 'local'

pretrain_256: 'checkpoints/vit_256_small_dino.pth'
freeze_256: True

pretrain_4096: 'checkpoints/vit_4096_xs_dino.pth'
freeze_4096: True