data_dir: 'data/'
output_dir: 'output/'

dataset_name: 'tcga_brca'
data_csv: 'data/data.csv'

level: 'global'

size: 'small'
num_classes: 1
nepochs: 20
eval_every: 1
lr: 0.0001
lr_scheduler:
lr_step: 15
dropout: 0.25

pct: 0.1

train_batch_size: 1
tune_batch_size: 1

tracking: 'loss'
metric_objective: 'min'

wandb:
  project: 'hipt'
  exp_name: 'training'
  username: 'clemsg'