data_dir: 'data/'
output_dir: 'output/'
features_dir: 'output/features/'

level: 'global'

size: 'small'
num_classes: 1
nepochs: 20
eval_every: 1
lr: 0.0001
lr_scheduler:
lr_step: 15
dropout: 0.25

train_batch_size: 1
tune_batch_size: 1

tracking: 'loss'
metric_objective: 'min'