data_dir: 'data'
output_dir: 'output'

dataset_name: 'tcga_brca'
data_csv: '${data_dir}/${dataset_name}/data.csv'
slide_list: '${data_dir}/${dataset_name}/tmp_list.txt'

fold_num: -1
level: 'global'

size: 'small'
num_classes: 1
nepochs: 20
eval_every: 1
lr: 0.0001
lr_scheduler:
lr_step: 15
dropout: 0.25

pct:

train_batch_size: 1
tune_batch_size: 1

tracking: 'auc'
metric_objective: 'max'

wandb:
  project: 'hipt'
  exp_name: 'toy_training'
  username: 'clemsg'