data_dir: 'data'
output_dir: 'output'
features_dir:

dataset_name: 'tcga_brca'
data_csv:
slide_list:
# data_csv: '${data_dir}/${dataset_name}/data.csv'
# slide_list: '${data_dir}/${dataset_name}/slide_list.txt'

fold_num: 0
level: 'local'

num_classes: 2
nepochs: 50
tune_every: 1

weighted_sampling: True
gradient_clipping: 32

pct:

train_batch_size: 1
tune_batch_size: 1

save_all: False

model:
  img_size: 224
  pretrain_4096: 'checkpoints/vit_4096_xs_dino.pth'
  freeze_4096: True
  freeze_4096_pos_embed: False
  dropout: 0.25

optim:
  name: 'adam'
  lr: 2e-4
  wd: 1e-5
  lr_scheduler:
    name:
    step_size: 10
    gamma: 0.5

early_stopping:
  enable: True
  tracking: 'loss'
  min_max: 'min'
  patience: 10
  min_epoch: 50

wandb:
  project: 'hipt'
  exp_name: 'toy_training'
  username: 'clemsg'