data_dir: 'data'
output_dir: 'output'
features_dir: '/home/user/code/git/opensource/tmp/HIPT/3-Self-Supervised-Eval/embeddings_slide_lib/embeddings_slide_lib/vit256mean_tcga_slide_embeddings'

dataset_name: 'tcga_brca'
data_csv: '${data_dir}/${dataset_name}/data.csv'
slide_list:

fold_num: 0
level: 'global'
pretrain_4096:
freeze_4096:

num_classes: 2
nepochs: 50
tune_every: 1
lr: 2e-4
lr_scheduler:
lr_step: 15
wd: 1e-5
dropout: 0.25
weighted_sampling: True
gradient_clipping: 32

pct:

train_batch_size: 1
tune_batch_size: 1

save_all: False

early_stopping:
  enable: True
  tracking: 'loss'
  min_max: 'min'
  patience: 10
  min_epoch: 30

wandb:
  project: 'hipt'
  exp_name: 'toy_training'
  username: 'clemsg'