defaults:
  - single
  - _self_

data:
  fold_dir: '/home/user/dataset/witali-liver/splits/fold_0'

features_dir: 'output/witali-liver/features/global'
output_dir: 'output'
experiment_name: 'debug'
level: 'global'

nepochs: 50
label_name: 'OS'
nbins: 4

testing:
  run_testing: True
  retrieve_checkpoint: 'latest'

model:
  agg_method: 'concat'
  slide_pos_embed:
    use: True
    learned: False
    type: '1d'
    max_seq_len: 3000
