defaults:
  - single
  - _self_

data:
  fold_dir: ''

level: 'global'

nepochs: 50
num_classes: 2

model:
  dropout: 0.25

optim:
  name: 'adam'
  lr: 2e-4
  wd: 1e-5

wandb:
  exp_name: 'training_multifold'